### ISSUE TITLE
Deluge unable to start.

### ISSUE THREAD

**Issue by testbughub** [ebrianne/docker-deluge-openvpn#15]
**Describe the problem**
Container starts, but not deluge.
It was working fine yesterday.

**Add your docker run command**
_docker-compose.yaml:_
```
version: '3.3'

services:
    deluge-openvpn:
        container_name: deluge
        image: ebrianne/docker-deluge-openvpn
        cap_add:
            - NET_ADMIN
        volumes:
            - '/home/myusername/L4/docker/deluge/config/:/config'
            - '/home/myusername/L4/docker/deluge/download/:/download'
            - '/media/myusername/2:/mnt/hdd2'
            - '/media/myusername/4:/mnt/hdd4'
            - '/media/myusername/5:/mnt/hdd5'
        environment:
            - OPENVPN_PROVIDER=MULLVAD
            - OPENVPN_CONFIG=se_got
            - OPENVPN_USERNAME=myusername
            - OPENVPN_PASSWORD=m
            - LOCAL_NETWORK=192.168.0.0/16
            - PUID=1000
            - PGID=1000
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '8112:8112'
            - '58846:58846'
        restart: unless-stopped
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
```

**Logs**
[pastebin](https://pastebin.com/weQZFR4V)

**Host system:**
Linux Mint 20.3 "una" x64
