### ISSUE TITLE
New image with updated deluged

### ISSUE THREAD

**Issue by AntlerDM** [ebrianne/docker-deluge-openvpn#18]
**Is your feature request related to a problem? Please describe.**
No. Container is working as expected. See Additional Context.

**Describe the solution you'd like**
Requesting a new image that contains the current version of deluged.

**Describe alternatives you've considered**
I have tried updating deluged on an existing container with standard update commands and installing the new version, but it always results in a non-functional container.

**Additional context**
The reason behind the request is that I am seeing an increase in torrents that stop at 99.9% and wonder if the new version of deluged would help with this.

Alternatively, is there a safe or recommended way to update deluged in an existing container or image?

**Comment by mind-overflow** [comment]
Hello,
just a heads up that I forked the project and updated the baseline image to Ubuntu 22.04 LTS + a pipeline to always keep the latest Deluge version installed at tag `latest` (currently Deluge v2.1.1).

This is the image: [bottledpills/deluge-openvpn](https://hub.docker.com/repository/docker/bottledpills/deluge-openvpn/tags)
This is the source: [bea/docker-deluge-openvpn](https://git.beatrice.wtf/bea/docker-deluge-openvpn)

I'm still working on cleaning everything up but the latest image is already fully working and functional.

This is an example deployment on Kubernetes via NordVPN:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: deluge
          image: bottledpills/deluge-openvpn:latest
          securityContext:
            privileged: true  # Often required for TUN/TAP devices
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8112
              protocol: TCP
            - containerPort: 6881
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
            - containerPort: 58846
              protocol: TCP
          env:
            - name: TZ
              value: Etc/UTC
            - name: DELUGE_LOGLEVEL
              value: "error"
            - name: OPENVPN_PROVIDER
              value: "nordvpn"
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: password
            - name: LOCAL_NETWORK
              value: "10.10.10.0/24,10.244.0.0/24"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: dev-net-tun
              mountPath: /dev/net/tun
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: deluge-config
        - name: downloads
          persistentVolumeClaim:
            claimName: deluge-downloads
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config
  namespace: deluge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-downloads
  namespace: deluge
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: deluge
  namespace: jellyfin
spec:
  selector:
    app: deluge
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8112
    - name: torrent-tcp
      protocol: TCP
      port: 6881
      targetPort: 6881
    - name: torrent-udp
      protocol: UDP
      port: 6881
      targetPort: 6881
    - name: daemon
      protocol: TCP
      port: 58846
      targetPort: 58846
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge-ingress
  namespace: deluge
  annotations:
    kubernetes.io/ingress.class: "nginx"
    acme.cert-manager.io/disable-http01-propagation-check: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - torrent.your.domain
    secretName: deluge-tls
  rules:
  - host: torrent.your.domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deluge
            port:
              number: 80

```
