### ISSUE TITLE
Container Health Check Fails due to Deluge Daemon Not Running

### ISSUE THREAD

**Issue by CardcaptorRLH85** [ebrianne/docker-deluge-openvpn#7]
**Describe the problem**

The container is reporting as being unhealthy due to the deluge daemon not running.  However, when I try to start deluged manually, I see the following:
```
 03:34:15 [ERROR   ][deluge.core.daemon_entry      :128 ] Cannot start deluged, listen port in use.
 Check for other running daemons or services using this port: localhost:58846
```
When I check to see what is running on that port I see this:
```
root@45cba2b98c02:/# netstat -ltnp | grep 58846
tcp        0      0 0.0.0.0:58846           0.0.0.0:*               LISTEN      -
root@45cba2b98c02:/#
```
The blank in the place of the name of the offending process has led me to a wall in my ability to self-diagnose the issue here.
**Add your docker run command**

```
---
version: "3.8"
services:
    deluge-openvpn:
        container_name: Deluge-OpenVPN
        image: ebrianne/docker-deluge-openvpn:latest
        network_mode: bridge
        volumes:
            - /volume1/docker/Deluge-OpenVPN:/config
            - /volume1/Downloads:/downloads
            - /volume1/Documents/Torrents:/torrents
        environment:
            - PUID=1029
            - PGID=65537
            - OPENVPN_PROVIDER=MULLVAD
            - OPENVPN_CONFIG=mullvad_us_udp
            - OPENVPN_USERNAME=[REDACTED]
            - OPENVPN_PASSWORD=[REDACTED]
            - LOCAL_NETWORK=192.168.2.0/24
            - CREATE_TUN_DEVICE=true
            - HEALTH_CHECK_HOST=google.com
        cap_add:
            - NET_ADMIN
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        logging:
            driver: json-file
            options:
                max-size: 16m
        ports:
            - '8112:8112'
            - '58846:58846'
            - '58946:58946'
        restart: unless-stopped
```
**Logs**

Here is the most recent healthcheck log specifically.  According to Portainer, it has failed 47 times since the last container start.
```
PING google.com (142.250.191.110) 56(84) bytes of data. 64 bytes from ord38s28-in-f14.1e100.net (142.250.191.110): icmp_seq=1 ttl=115 time=32.8 ms --- google.com ping statistics --- 1 packets transmitted, 1 received, 0% packet loss, time 0ms rtt min/avg/max/mdev = 32.860/32.860/32.860/0.000 ms PING google.com (142.250.191.110) 56(84) bytes of data. 64 bytes from ord38s28-in-f14.1e100.net (142.250.191.110): icmp_seq=1 ttl=115 time=22.5 ms --- google.com ping statistics --- 1 packets transmitted, 1 received, 0% packet loss, time 0ms rtt min/avg/max/mdev = 22.520/22.520/22.520/0.000 ms Network is up deluge-daemon process not running
```
**Host system:**

This container is on my Synology DS220+ NAS running DSM 7 and Docker 20.10.3.
